### Get products
GET http://localhost:8090/shop/products
###
POST http://localhost:8090/shop/product
content-type: application/json

{
    "id": 4, 
    "name": "Laptop Charger", 
    "price": 50.00
}
###
POST http://localhost:8090/shop/order
content-type: application/json

{
    "productId": 1, 
    "quantity": 1
}
###
GET http://localhost:8090/shop/order/0